import { CategoryType } from '@/types/categories'
import { FontListItemType } from '@/types/fonts'

export const temptation = []

export const dummy: FontListItemType[] = [
  {
    id: 1,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 2,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 3,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 4,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 5,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 6,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 7,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 8,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 9,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
  {
    id: 10,
    name: 'Noto Sans KR',
    description: 'sans-serif',
    image: '/assets/logo.png',
    author: 'google',
    createdAt: '2021-01-01',
    commerce: true,
  },
]

export const Categories: CategoryType[] = [
  {
    id: '1',
    name: '최신',
    slug: 'font',
    description: '최신 폰트',
    image: '/images/categories/font.png',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
  },
  {
    id: '2',
    name: '브랜드',
    slug: 'theme',
    description: '브랜드별 인기 폰트',
    image: '/images/categories/theme.png',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
  },
  {
    id: '3',
    name: '트렌드',
    slug: 'font',
    description: '요즘 트렌드를 반영한 폰트',
    image: '/images/categories/font.png',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
  },
  {
    id: '4',
    name: '연령순',
    slug: 'theme',
    description: '연령별 인기 폰트',
    image: '/images/categories/theme.png',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
  },
]
